language: r

notifications:
  slack:
    secure: M/pDn42cC/+pDT09QnG5h9Ll9KywbbUSTmgBLsSlfm9nj70oreqksG23jD6aLLc2VKNatBATgpt9FqtSVziqWjvERTLobAeYDz35VHTE8GNNbwKA09tLgMl9B1YM4+jlLWBKOz1iU5TmPRHxwxAVxtTTgyxoH5lMWjn4jGL0llg=
  slack: neopaleon:m8hd2mRserZ1tb0p9BsVFATe
