language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
- travis_wait mvn install
script: "./travis-tool.sh run_tests"
on_failure:
- "./travis-tool.sh dump_logs"
notifications:
  slack:
    secure: M/pDn42cC/+pDT09QnG5h9Ll9KywbbUSTmgBLsSlfm9nj70oreqksG23jD6aLLc2VKNatBATgpt9FqtSVziqWjvERTLobAeYDz35VHTE8GNNbwKA09tLgMl9B1YM4+jlLWBKOz1iU5TmPRHxwxAVxtTTgyxoH5lMWjn4jGL0llg=
